# Generated by Django 3.1.5 on 2021-01-13 21:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210113_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 21, 22, 41, 433337, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 21, 22, 41, 432373, tzinfo=utc)),
        ),
    ]
