# Generated by Django 3.1.5 on 2021-01-14 12:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210114_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 14, 12, 53, 15, 860162, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 14, 12, 53, 15, 859122, tzinfo=utc)),
        ),
    ]
